import { Fira_Sans, Fira_Mono, Alegreya, Fraunces } from "next/font/google"

/**
 * The four faces the whole site draws from. Change a face here and every
 * rendition that references it changes with it — this is the only file that
 * names a typeface.
 *
 * All four are *humanist*: their skeletons come from Renaissance pen forms
 * rather than from the drafting compass. That is what makes a page read as
 * written by a person instead of generated by one — open apertures, a
 * two-storey g, stroke weight that swells and thins the way a nib does, and
 * real italics that are drawn rather than slanted.
 *
 *   sans    Fira Sans — Erik Spiekermann & Carrois Corporate. The humanist
 *           end of the grotesque family: Frutiger's lineage, warmer and more
 *           legible at small sizes than the Helvetica/Inter neo-grotesques,
 *           and still disciplined enough for a Swiss grid.
 *   serif   Alegreya — Juan Pablo del Peral, Huerta Tipográfica. Explicitly
 *           calligraphic, designed for long-form literary text; picked for
 *           ATypI's "Fonts of the Decade" and a TDC Certificate of Excellence
 *           in Type Design.
 *   soft    Fraunces — a "wonky" old-style display face with optical-size and
 *           softness axes. Used only at display sizes, where its irregularity
 *           reads as personality rather than noise.
 *   mono    Fira Mono — Fira Sans's own monospace companion, so the technical
 *           renditions stay in the same voice as the rest of the site.
 */

export const fontSans = Fira_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-sans",
  display: "swap",
})

export const fontSerif = Alegreya({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-serif",
  display: "swap",
})

export const fontSoft = Fraunces({
  subsets: ["latin"],
  axes: ["SOFT", "WONK", "opsz"],
  variable: "--font-soft",
  display: "swap",
})

export const fontMono = Fira_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-mono",
  display: "swap",
})

/** Put this on <html> — see the note in app/layout.tsx about why not <body>. */
export const fontVariables = [fontSans.variable, fontSerif.variable, fontSoft.variable, fontMono.variable].join(" ")
